### ISSUE TITLE
How to classify wikidata entries into our RDB

### ISSUE THREAD

**Issue by amaurymartiny** [chronhq/backend#23]
Our RDB architecture proposes 6 types of political relations. https://github.com/chronhq/backend/blob/220f34a6ea01a397ea7d940661d14737fccbc0d2/project/api/models.py#L82-L87
Wikidata proposes a lot more. This issue serves to discuss how to classify wikidata's political relations into our 6 categories.

**DIRECT**
Satisfies
- has property [located in the administrative territorial entity](https://www.wikidata.org/wiki/Property:P131)

Example: https://www.wikidata.org/wiki/Q12130

**DIRECT_OCCUPIED**
Satisfies:
- instance of [occupied territoriry](https://www.wikidata.org/wiki/Q2577883)

Example: https://www.wikidata.org/wiki/Q156111

**DIRECT_DISPUTED**
Satisfies:
- instance of [disputed territoriry](https://www.wikidata.org/wiki/Q15239622)

Example: https://www.wikidata.org/wiki/Q43100

**INDIRECT**
Satifies
- instance of any subclass of [dependent territory](http://tinyurl.com/ycjpqy3b) or [client state](http://tinyurl.com/ybkh7gus)

Example: https://www.wikidata.org/wiki/Q1709185

**INDIRECT_DISPUTED**
Satisfies:
- instance of any subclass of [dependent territory](http://tinyurl.com/ycjpqy3b) or [client state](http://tinyurl.com/ybkh7gus)
- instance of [disputed territoriry](https://www.wikidata.org/wiki/Q15239622)

Example: TODO

**GROUP**
Satisfies:
- has property [member of](https://www.wikidata.org/wiki/Property:P463)

Example: https://www.wikidata.org/wiki/Q142

---

Let's improve this document together.

**Comment by MiklerGM** [comment]
> Our RDB architecture proposes 6 types of political relations.

I thought we were decided that we are not storing `occupied` status in our call with every one.
We do not need `direct-occupied` relation in our db, this is a `direct` relation, so it would be marked as a sub-region of host-country. Information about `control-degree`'s status can be fetched from wikidata directly.

Remember, we were discussing this here:
https://chronhq.slack.com/archives/CDMV5K3M2/p1543239208016300?thread_ts=1543217496.008500&cid=CDMV5K3M2

**Comment by MiklerGM** [comment]
Pasting original thread here.

> Michael Orlov [Nov 26th at 8:31 AM]
@Amaury Martiny Correct me, 'occupied' state works as alias for other inner 'districts'.
Example: Second Polish Republic, with all regions (mazowieckie, łódzkie, etc)
SPR (Top level PE) occupied by Germany - direct-occupation.
SPR regions are still under the direct relation with Poland, right?

>What do we do with fact, that Second Polish Republic dissolution date is in 1939? In this case we will keep active the country that is not existing at this time period. (edited)


>14 replies
>Amaury Martiny [26 days ago]
I was thinking create an entity "Poland under Nazi Germany", but it exists: https://www.wikidata.org/wiki/Q156111
wikidata.org
Residual Poland General Governorate
general governorate of Nazi Germany
 


>Amaury Martiny [26 days ago]
All regions/voivodeships etc will be under SPR until 1939, and then under Q156111 from 1939-1945


>Michael Orlov [26 days ago]
In this case we do not mark Poland as occupied, it's a separate PE then. In all other cases we should do the same (imo). So we can remove the `disputed-occupied` type :slightly_smiling_face: (edited)


>Amaury Martiny [26 days ago]
By Poland, do you mean Q36 or Q156111?
>- Q36 -> I don't know what to do about this tbh...
>- Q156111 -> It's a PE, and it is `direct-occupied` by Nazi Germany, so we need `direct-occupied`.

>Or maybe I misunderstood your point?


>Michael Orlov [26 days ago]
In my vision Evolution of Poland should be like this:

>Q207272 (SPE 1918-1938) is a predecessor for: Q156111
>Q156111 (RPGG 1939-1945) is a predecessor for: Q36
>~Q36 (Poland 11 November 1918 -~ _// according to wikidata_
>Q36 (1945 - today)

>without the gap in history of existence
Q156111 is under `direct-full` control of Germany. The occupation status is in the PE's 'instance of' status (edited)


>Amaury Martiny [26 days ago]
Ah ok, got it. So the `control_degree` is in PE table, like before? And in PR, type is `direct|indirect|group`?

>I think it could work too. But in the case of British HK, 1841-1997, but only occupied in 1941-1945 by Japan. In this case we need to create another entity called "Japanese-occupied HK". (edited)


>Michael Orlov [26 days ago]
Why do we need `control_degree`? It's already on wikidata's page
Pasted image at 2018-11-26, 4:22 PM
![image](https://user-images.githubusercontent.com/61106/50372973-2696c280-05d8-11e9-9d92-e866bd57c1db.png)



>Amaury Martiny [26 days ago]
Because it's needed to generate vector tiles (striped or not). If we remove this field, then when we generate the GeneratedTables, we need to make `N` queries to wikidata, `N=number of TEs`


>Michael Orlov [26 days ago]
If MVT is only a Polygon it does not know anything about TE's status. All this information about stripes and colors are in the style.json file



>Michael Orlov [26 days ago]
We should keep all the information about TE cached, otherwise we will have country named Q666 and that's all.


>Amaury Martiny [26 days ago]
OK for the style.json, then we don't need indeed `control_type` at all. So we go simple, only `type=direct|indirect|group` in PR?


>Amaury Martiny [26 days ago]
Yes, agreed TE should be cached. Basically every line in the google sheet will have one line in the cache table.


>Michael Orlov [26 days ago]
Ok, if country has two direct relations it's disputed?


>Amaury Martiny [26 days ago]
>Yes. For me that would work:
>- has 2 direct PR -> it means disputed
>- has 1 direct PR, and wikidata says `occupied territory` -> it's occupied
>- has 1 direct PR, and wikidata says nothing else -> it's a normal sub-region
