### ISSUE TITLE
Upsert cached data entities

### ISSUE THREAD

**Issue by MiklerGM** [chronhq/backend#79]
This issue is related to #77
Due to new constraints #75 implemented in #76 and the fact that `rank` field is computed based variable data fetched from wikidata.

- [x] Our need is to update existing entities without flushing database.
- [ ] Optimize number of queries to wikidata needed to perform full database update.
- [ ] Do additional validation and more verbose output when rank calculation has failed https://github.com/chronhq/backend/blob/master/project/api/models.py#L152

UPD:

Cross link to microservices https://github.com/chronhq/microservices/issues/16

**Comment by whirish** [comment]
The first can be done by sending a blank PATCH query to `/api/cached-data/<pk>/`

**Comment by whirish** [comment]
`Do additional validation and more verbose output when rank calculation has failed`
This currently fails because one of the multipliers (incoming * sitelinks * outcoming) is not present in the query. When multiplying them together this would just result in a product of 0 anyway, which is the explanation behind the line you linked. If we change the alg to adding I guess we can just set the missing index to 0 and add the others.

**Comment by MiklerGM** [comment]
I will close this, because we need to keep ranking algorithm on backend, and we have an issue for upserting data in microservices chronhq/microservices#16
